ame: Build Test

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npx electron-builder --mac --arm64 --x64 --publish never

      - run: ls -R dist